<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot parameters -->
    <xacro:property name="rho" value="0.5" />
    <xacro:property name="wheel_diameter" value="0.100" />
    <xacro:property name="wheel_xoffset" value="0.070" />
    <xacro:property name="wheel_separation" value="0.240" />

    <xacro:property name="base_x" value="0.300" />
    <xacro:property name="base_y" value="0.200" />
    <xacro:property name="base_z" value="0.020" />
    <xacro:property name="base_vol" value="${base_x * base_y * base_z}" />
    <xacro:property name="base_mass" value="${1000.0 * base_vol * rho}" />
    <xacro:property name="base_Ixx" value="${(1/12) * base_mass * (base_y**2 + base_z**2)}" />
    <xacro:property name="base_Iyy" value="${(1/12) * base_mass * (base_x**2 + base_z**2)}" />
    <xacro:property name="base_Izz" value="${(1/12) * base_mass * (base_x**2 + base_y**2)}" />

    <xacro:property name="wheel_h" value="0.020" />
    <xacro:property name="wheel_r" value="${wheel_diameter / 2}" />
    <xacro:property name="wheel_vol" value="${pi * wheel_r**2 * wheel_h}" />
    <xacro:property name="wheel_mass" value="${1000.0 * wheel_vol * rho}" />
    <xacro:property name="wheel_Ixx" value="${(1/12) * wheel_mass * wheel_h**2}" />
    <xacro:property name="wheel_Izz" value="${(1/2) * wheel_mass * wheel_r**2}" />

</robot>
