<?xml version='1.0'?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find gazebo_test_inertial)/urdf/params.xacro" />
    <xacro:include filename="$(find gazebo_test_inertial)/urdf/wheel.xacro" />
    <xacro:include filename="$(find gazebo_test_inertial)/urdf/diffdrive.gazebo" />

        <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x} ${base_y} ${base_z}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x} ${base_y} ${base_z}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 ${base_z / 2}" />
            <mass value="${base_mass}" />
            <inertia ixx="${base_Ixx}" ixy="0" ixz="0"
                iyy="${base_Iyy}" iyz="0" izz="${base_Izz}" />
        </inertial>
    </link>

    <!-- Left drive wheel -->
    <xacro:wheel name="lwheel" joint_xyz="${wheel_xoffset} ${wheel_separation / 2} 0" />
    <!-- Right drive wheel -->
    <xacro:wheel name="rwheel" joint_xyz="${wheel_xoffset} ${-wheel_separation / 2} 0" />

</robot>
